---
- hosts: mnode2
  vars:
    maildir_path: /tmp/Maildir
    maildir: /home/student/maildir
    mail_package: postfix
    mail_service: postfix

  tasks:
  - block:
    - name: Create {{ maildir_path }}
      copy:
         src: "{{ maildir }}"
         dest: "{{ maildir_path }}"
         mode: 0755
    rescue:
    - name: Install mail packages
      apt: 
        name: "{{ item }}"
        state: latest
      with_items:
        - "{{ mail_package }}"
        - dovecat
    always:
    - name: start mail services
      service: 
        name: "{{ item }}"
        state: started
      with_items:
        - "{{ mail_service }}"
        - dovecat
      register: command_result
  - debug:
      var: command_result
