- hosts: all
  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: latest
    register: output
  - debug:
      var: "{{ output | to_nice_json }]"
  - name: Copy the template
    template:
      src: templates/nginx.j2
      dest: /etc/nginx/nginx.conf
    notify:
      - restart nginx
  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
