- name: intranet services
  hosts: mnode4
  become: yes
  tasks:
  - block:
    - name: Install latest httpd
      yum:
        name: httpd
        state: latest
    - name: Install latest firewalld
      yum:
        name: firewalld
        state: latest
  - block:
    - name: Enable and run httpd
      service: 
        name: httpd
        enabled: true
        state: started
    - name: enable and run firewalld
      service: 
        name: firewalld
        enabled: true
        state: started
  - block:
    - name: firewalld permist http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
  - block: 
    - name: Test html page
      copy: 
        content: "Welcome to the KOGINTEX ANSIBLE TRAINING intranet webpaage\n"
        dest: /var/www/html/index.html
  



       

