
---
- hosts: webservers
  vars:
    time_out: 180
    max_clients: 200
  remote_user: student
  tasks:
  - name: ensure apache is at the latest version
    yum: name=apache2 state=latest
  - name: write the apache config file
    template: src=templates/httpd.j2 dest=/etc/apache2/apache2.conf
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
